# yaml 
version: '3.3'
services:
  centos:
    environment:
      - DISPLAY=:0
    build:
      context: .
      dockerfile: centos.Dockerfile
    volumes:
      - /space/opt:/opt
      - /space/ubu:/home/ubu
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    container_name: centos
    command: ["ls"]


  #db:
    #image: mysql
