# yaml
version: '3.3'

# external volume by docker-lvm-plugin
volumes:
  docker_registry:
    external: true
  docker_gitea: 
    external: true
  docker_mysql:
    external: true
  docker_jenkins:
    external: true
  #ipa-data:
  #  external: true

#external network created by 'docker network create --subnet 172.20.0.0/16 mynet1'
networks:
  default:
    external:
      name: mynet1
#
services:
  #-tt-freeipa_2:
  #-tt-  build:
  #-tt-    context: .
  #-tt-    dockerfile: freeipa.Dockerfile
  #-tt-  hostname: ipa.ict-group.cn
  #-tt-  restart: always
  #-tt-  environment:
  #-tt-    - IPA_SERVER_IP=172.17.0.2
  #-tt-  #sysctls:
  #-tt-  #  - net.ipv6.conf.all.disable_ipv6 = 0
  #-tt-  volumes:
  #-tt-    - /home/ipa-data:/data:Z
  #-tt-    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #-tt-    - /dev/urandom:/dev/random:ro 
  #-tt-  ports:
  #-tt-  #  - 53:53/udp
  #-tt-  #  - 53:53
  #-tt-    - 80:80
  #-tt-    - 443:443
  #-tt-    - 389:389
  #-tt-    - 636:636
  #-tt-    - 88:88
  #-tt-    - 464:464
  #-tt-    - 88:88/udp
  #-tt-    - 464:464/udp
  #-tt-    - 123:123/udp
  
  freeipa:
    image: freeipa/freeipa-server:centos-8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    hostname: ipa.ict-group.cn
    restart: always
    volumes:
      - /home/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/urandom:/dev/random:ro
    networks:
      default:
        ipv4_address: 172.20.0.2
    ports:
    #  - 53:53/udp
    #  - 53:53
      - 80:80
      - 443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    environment:
      - IPA_SERVER_IP=172.20.0.2
    #this is one-time setup to update /home/ipa-data
    command: ["ipa-server-install", "-U", "--allow-zone-overlap", "--realm=ICT-GROUP.CN", "--ds-password=12345678", "--admin-password=12345678", "--no-ntp"]

  #-using-docker-
  #-using-docker-centos:
  #-using-docker-  environment:
  #-using-docker-    - DISPLAY=:0
  #-using-docker-  build:
  #-using-docker-    context: .
  #-using-docker-    dockerfile: centos.Dockerfile
  #-using-docker-  volumes:
  #-using-docker-    - /space/opt:/opt
  #-using-docker-    - /space/ubu:/home/ubu
  #-using-docker-    - /tmp/.X11-unix/:/tmp/.X11-unix/
  #-using-docker-  container_name: centos
  #-using-docker-  command: ["ls"]

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - docker_jenkins/:/var/jenkins_home:Z
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    network_mode: "host"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    #  JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'

  gitea:
    image: gitea/gitea:1.13.3
    #image: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    network_mode: "host"
    volumes:
      - docker_gitea:/data:Z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mysql
 
  mysql:
    #image: mysql:5.7
    image: mysql
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - docker_mysql:/var/lib/mysql:Z
    security_opt:
      - seccomp:unconfined
  registry:
    restart: always
    image: registry:2.3.0
    ports:
      - 5000:5000
    network_mode: "host"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_STORAGE_DELETE_ENABLED="true"
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      #REGISTRY_HTTP_SECRET: 11112222'
    volumes:
      - docker_registry:/var/lib/registry:Z
      - ~/certs:/certs
      #- /path/auth:/auth
