# yaml 
version: '3.3'

volumes:
  docker_registry:
    external: true
  ipa-data:
    external: true
    
services:
  freeipa:
    build:
      context:    docker-library-official-images/freeipa
      dockerfile: Dockerfile.centos-8
    container_name: freeipa
    volumes:
      - ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 53:53/udp
      - 53:53
      - 80:80
      - 443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp

  centos:
    environment:
      - DISPLAY=:0
    build:
      context: .
      dockerfile: centos.Dockerfile
    volumes:
      - /space/opt:/opt
      - /space/ubu:/home/ubu
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    container_name: centos
    command: ["ls"]


  #db:
    #image: mysql

  registry:
    # restart: always
    image: registry:2.3.0
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      #REGISTRY_HTTP_SECRET: 11112222'
    volumes:
      - docker_registry:/var/lib/registry
      - ~/certs:/certs
      #- /path/auth:/auth
