# yaml
version: '3.3'

# external volume by docker-lvm-plugin
volumes:
  docker_registry:
    external: true
  docker_gitea: 
    external: true
  docker_mysql:
    external: true
  docker_jenkins:
    external: true

services:
  #-using-vagrant-freeipa_2:
  #-using-vagrant-  build:
  #-using-vagrant-    context: .
  #-using-vagrant-    dockerfile: freeipa.Dockerfile
  #-using-vagrant-  hostname: ipa.ict-group.cn
  #-using-vagrant-  container_name: freeipa_2
  #-using-vagrant-  environment:
  #-using-vagrant-    - IPA_SERVER_IP=172.17.0.2
  #-using-vagrant-  #sysctls:
  #-using-vagrant-  #  - net.ipv6.conf.all.disable_ipv6 = 0
  #-using-vagrant-  volumes:
  #-using-vagrant-    #- ipa-data:/data:Z
  #-using-vagrant-    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #-using-vagrant-    - /dev/urandom:/dev/random:ro 
  #-using-vagrant-  ports:
  #-using-vagrant-  #  - 53:53/udp
  #-using-vagrant-  #  - 53:53
  #-using-vagrant-    - 80:80
  #-using-vagrant-    - 443:443
  #-using-vagrant-    - 389:389
  #-using-vagrant-    - 636:636
  #-using-vagrant-    - 88:88
  #-using-vagrant-    - 464:464
  #-using-vagrant-    - 88:88/udp
  #-using-vagrant-    - 464:464/udp
  #-using-vagrant-    - 123:123/udp
  #-using-vagrant-
  #-using-vagrant-freeipa:
  #-using-vagrant-  image: freeipa/freeipa-server:centos-8
  #-using-vagrant-  container_name: freeipa
  #-using-vagrant-  sysctls:
  #-using-vagrant-    - net.ipv6.conf.all.disable_ipv6=0
  #-using-vagrant-  hostname: ipa.ict-group2.cn
  #-using-vagrant-  volumes:
  #-using-vagrant-    - ipa-data:/data:Z
  #-using-vagrant-    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #-using-vagrant-    - /dev/urandom:/dev/random:ro 
  #-using-vagrant-  ports:
  #-using-vagrant-  #  - 53:53/udp
  #-using-vagrant-  #  - 53:53
  #-using-vagrant-    - 80:80
  #-using-vagrant-    - 443:443
  #-using-vagrant-    - 389:389
  #-using-vagrant-    - 636:636
  #-using-vagrant-    - 88:88
  #-using-vagrant-    - 464:464
  #-using-vagrant-    - 88:88/udp
  #-using-vagrant-    - 464:464/udp
  #-using-vagrant-    - 123:123/udp
  #-using-vagrant-  environment:
  #-using-vagrant-    - IPA_SERVER_IP=172.17.0.2
  #-using-vagrant-  command: ["ipa-server-install", "-U", "--allow-zone-overlap", "--realm=ICT-GROUP2.CN", "--ds-password=12345678", "--admin-password=12345678", "--no-ntp"]
  #-using-vagrant-
  #-using-vagrant-centos:
  #-using-vagrant-  environment:
  #-using-vagrant-    - DISPLAY=:0
  #-using-vagrant-  build:
  #-using-vagrant-    context: .
  #-using-vagrant-    dockerfile: centos.Dockerfile
  #-using-vagrant-  volumes:
  #-using-vagrant-    - /space/opt:/opt
  #-using-vagrant-    - /space/ubu:/home/ubu
  #-using-vagrant-    - /tmp/.X11-unix/:/tmp/.X11-unix/
  #-using-vagrant-  container_name: centos
  #-using-vagrant-  command: ["ls"]

  jenkins:
    #image: jenkins/jenkins:lts
    image: jenkins/jenkins
    volumes:
      - docker_jenkins/:/var/jenkins_home:Z
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    network_mode: "host"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    #  JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'

  gitea:
    image: gitea/gitea:1.13.3
    #image: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    network_mode: "host"
    volumes:
      - docker_gitea:/data:Z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
 
  mysql:
    #image: mysql:5.7
    image: mysql
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - docker_mysql:/var/lib/mysql:Z
    security_opt:
      - seccomp:unconfined
  registry:
    restart: always
    image: registry:2.3.0
    ports:
      - 5000:5000
    network_mode: "host"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_STORAGE_DELETE_ENABLED="true"
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      #REGISTRY_HTTP_SECRET: 11112222'
    volumes:
      - docker_registry:/var/lib/registry:Z
      - ~/certs:/certs
      #- /path/auth:/auth
